name: finance_manager
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI iOS style
  cupertino_icons: ^1.0.8

  # Hive para almacenamiento rápido
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Path Provider para rutas seguras
  path_provider: ^2.1.2

  # SQLite para base de datos robusta
  sqflite: ^2.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
# Para generar adaptadores de Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
flutter:
  uses-material-design: true

